let item = [
    {
        id:570940,
        title:"DARK SOULS™: REMASTERED",
        description:"《黑暗之魂》系列第一部，重制之后画质和流畅度提升，保留了原汁原味的设计，精巧设计的箱庭地图，让你有一种山穷水复疑无路，柳暗花明又一村的感觉。",
        score:"9.0",
        achievement:19,
        achievement_total:42,
        time:56,
    },
    {
        id:335300,
        title:"DARK SOULS™ II: Scholar of the First Sin",
        description:"《黑暗之魂》系列第二部，并非由初代作者宫崎英高主导，游戏机制改动较大，敌人数量不合理，但是如蜜和绿袍女将会给你带来温暖。",
        score:"7.5",
        achievement:18,
        achievement_total:38,
        time:31.8,
    },
    {
        id:374320,
        title:"DARK SOULS™ III",
        description:"《黑暗之魂》系列第三部，作为系列终曲，该部画面手感对比前两作都有了极大提升，地图依旧是箱庭设计，场景转换自然，背景音乐十分动人，在游玩途中会有身临其境之感。",
        score:"9.5",
        achievement:38,
        achievement_total:43,
        time:64,
    },
    {
        id:1245620,
        title:"艾尔登法环",
        description:"宫崎英高主题乐园，魂类游戏集大成之作！主人公性能对比有极大提升，玩法自然也多了起来，法术战技很炫酷，开放地图区域很大但也保留了魂类游戏优秀的箱庭地图设计，剧情一如既然‘碎片化叙事’，令人浮想联翩。",
        score:"9.0",
        achievement:42,
        achievement_total:42,
        time:152.6,
    },
    {
        id:1091500,
        title:"赛博朋克2077",
        description:"《巫师》系列开发商CDPR推出第一人称未来科技游戏，宣发工作十足，剧情节奏引人入胜，游戏性比较一般，更推荐其衍生作品《赛博朋克：边缘行者》。",
        score:"7.5",
        achievement:44,
        achievement_total:44,
        time:114.1,
    },
    {
        id:239140,
        title:"Dying Light",
        description:"爽快的第一人称丧尸题材游戏，胆小勿入，优质的剧情，足量的流程，物美价廉。",
        score:"8.5",
        achievement:66,
        achievement_total:78,
        time:102.4,
    },
];
const size = item.length;